jobs:
  test:
    description: "Run tests with jest via CI"
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test
version: 2.1
workflows:
  version: 2
  test:
    jobs:
      - test